config/routes.rb
Chatty::Engine.routes.draw do
  namespace :admin do
    resources :chats
  end

  resources :chats do
    member do
      get :messages
      post :handle
      post :close
    end
  end

  resources :messages
end

app/models/chatty/chat.rb
class Chatty::Chat < ActiveRecord::Base
  include PublicActivity::Model
  tracked
  
  belongs_to :resource, :polymorphic => true
  belongs_to :user, :polymorphic => true
  has_many :messages
  
  validates_presence_of :user
  accepts_nested_attributes_for :messages
  
  state_machine :state, :initial => :new do
    event :handle do
      transition [:new, :closed] => :handled
    end
    
    event :close do
      transition :handled => :closed
    end
  end
  
  def json
    return {
      :id => id,
      :state => state
    }
  end
  
  def self.translated_states
    return {
      _("New") => "new",
      _("Handled") => "handled",
      _("Closed") => "closed"
    }
  end
end

app/models/chatty/message.rb
class Chatty::Message < ActiveRecord::Base
  belongs_to :chat
  belongs_to :user, :polymorphic => true
  
  validates_presence_of :chat, :user, :message
  validate :validate_is_chat_open
  
  def json
    return {
      :id => id,
      :message => message,
      :user_id => user.id,
      :user_name => (user[:name].presence || user[:email].presence || user.id),
      :created_at => created_at.strftime("%Y-%m-%d %H:%M:%S")
    }
  end
  
private
  
  def validate_is_chat_open
    if chat.state != "handled"
      errors.add(:chat_id, _("is not open for new messages in that state: %{chat_state}", :chat_state => chat.translated_state))
    end
  end
end

app/controllers/chatty/admin_chats_controller.rb
class Chatty::AdminChatsController < Chatty::ApplicationController
  before_filter :set_chat, only: [:handle, :show]

  def index
    @ransack_params = params[:q] || {}
    @ransack = Chatty::Chat.ransack(@ransack_params)
    @chats = @ransack.result.order(:id).reverse_order
  end

  def show
  end

  def handle
    @chat.handle!
    @chat.create_activity key: "chatty/chat.handled", owner: current_user

    redirect_to admin_chat_path(@chat)
  end

private

  def set_chat
    @chat = Chatty::Chat.find(params[:id])
  end
end

app/controllers/chatty/application_controller.rb
class Chatty::ApplicationController < ApplicationController
  
end

app/controllers/chatty/chats_controller.rb
require_dependency "chatty/application_controller"

class Chatty::ChatsController < Chatty::ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy, :messages, :handle, :close]

  def index
    @ransack_params = params[:q] || {}
    @ransack = Chatty::Chat.ransack(@ransack_params.clone)
    @chats = @ransack.result.order(:id).reverse_order
  end

  def show
    respond_to do |format|
      format.json { render(json: {chat: @chat.json}) }
      format.html { render :show }
    end
  end

  def new
    @chat = Chatty::Chat.new
  end

  def edit
  end

  def create
    @chat = Chatty::Chat.new(chat_params)

    if @chat.save
      redirect_to @chat, notice: 'Chat was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @chat.update(chat_params)
      redirect_to @chat, notice: 'Chat was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @chat.destroy
    redirect_to chats_url, notice: 'Chat was successfully destroyed.'
  end

  def messages
    @messages = @chat.messages
    render partial: "messages", layout: false
  end

  def handle
    @chat.handle!
    @chat.create_activity key: "chatty/chat.handled", owner: current_user
    redirect_to chat_path(@chat)
  end

  def close
    @chat.close
    @chat.create_activity key: "chatty/chat.closed", owner: current_user
    redirect_to chat_path(@chat)
  end

private

  def set_chat
    @chat = Chatty::Chat.find(params[:id])
    authorize! action_name.to_sym, @chat
  end

  def chat_params
    params.require(:chat).permit(:user_type, :user_id, :resource_type, :resource_id)
  end
end

app/controllers/chatty/messages_controller.rb
class Chatty::MessagesController < Chatty::ApplicationController
  def new
    spawn_message
    render :new, :layout => false
  end
  
  def create
    spawn_message
    
    if @message.save
      render :json => {
        :success => true
      }
    else
      render :json => {
        :success => false,
        :errors => @message.errors.full_messages.join(". ")
      }
    end
  end
  
  def index
    @ransack_params = params[:q] || {}
    @ransack = Chatty::Message.ransack(@ransack_params)
    @messages = @ransack.result.order(:created_at, :id)
    
    respond_to do |format|
      format.json { render(:json => {:messages => messages_json(@messages)}) }
    end
  end
  
private
  
  def spawn_message
    if params[:message]
      @message = Chatty::Message.new(message_params)
    else
      @message = Chatty::Message.new
    end
    
    @message.user = current_user
    @message.chat_id = message_params[:chat_id]
  end
  
  def message_params
    params.require(:message).permit(:chat_id, :message)
  end
  
  def messages_json messages
    @messages.map do |message|
      message_json = message.json
      
      if message.user == current_user
        message_json[:self] = true
      else
        message_json[:self] = false
      end
      
      message_json
    end
  end
end

app/helpers/chatty/application_helper.rb
module Chatty::ApplicationHelper
  include ::SimpleFormRansackHelper
  
  def method_missing(method, *args, &block)
    return main_app.send(method, *args, &block) if main_app.respond_to?(method)
    super
  end
end

app/helpers/chatty/chats_helper.rb
module Chatty::ChatsHelper
  CHATTY_CHAT_ALLOWED_KEYS = [:data]
  def chatty_chat chat, args = {}
    args.each do |key, val|
      raise ArgumentError, "Invalid key: #{key}" unless CHATTY_CHAT_ALLOWED_KEYS.include?(key)
    end

    data = {
      chat_id: chat.id,
      signed_in: signed_in?,
      can_add_messages: can?(:new, Chatty::Message),
      need_to_be_signed_in_message: _("You need to be signed in to write messages."),
      not_allowed_to_add_messages_message: _("You are not allowed to write messages."),
      waiting_to_connect_message: _("Waiting to connect..."),
      waiting_to_be_handled_message: _("Waiting to be handled..."),
      chat_is_closed_message: _("This chat is closed.")
    }

    data = data.merge(args[:data]) if args[:data]

    content_tag(:div, nil, {
      class: "chatty_chat",
      data: data
    })
  end
end

app/views/chatty/admin_chats/index.html.haml
%h1= _("Chats")

= simple_search_form_for @ransack, @ransack_params do |f|
  = f.input :handled_eq, :as => :select, :collection => {_("Not handled") => "", _("Handled") => "1"}
  = f.submit _("Search")

%table
  %thead
    %tr
      %th= Chatty::Chat.human_attribute_name(:id)
      %th= Chatty::Chat.human_attribute_name(:handled)
      %th= Chatty::Chat.human_attribute_name(:created_at)
  %tbody
    - @chats.each do |chat|
      %tr
        %td= link_to chat.id, admin_chat_path(chat)
        %td= chat.handled? ? _("Yes") : _("No")
        %td= l(chat.created_at, :format => :long)
    - if @chats.none?
      %tr
        %td{:colspan => 3}
          = _("No chats was found.")

app/views/chatty/chats/index.html.haml
%h1= _("Chats")

= simple_search_form_for @ransack, @ransack_params do |f|
  = f.input :state_eq, :as => :select, :collection => Chatty::Chat.translated_states
  = f.submit _("Search")

%table
  %thead
    %tr
      %th= Chatty::Chat.human_attribute_name(:id)
      %th= Chatty::Chat.human_attribute_name(:handled)
      %th= Chatty::Chat.human_attribute_name(:created_at)
  %tbody
    - @chats.each do |chat|
      %tr
        %td= link_to chat.id, chat_path(chat)
        %td= chat.handled? ? _("Yes") : _("No")
        %td= l(chat.created_at, :format => :long)
    - if @chats.none?
      %tr
        %td{:colspan => 3}
          = _("No chats was found.")

app/views/chatty/chats/show.html.haml
%h1= _("Show chat")

= chatty_chat(@chat)

- if @chat.can_handle? && can?(:handle, @chat)
  = link_to _("Handle"), handle_chat_path(@chat), :method => :post, :data => {:confirm => _("Are you sure?")}

- if @chat.can_close? && can?(:close, @chat)
  = link_to _("Close"), close_chat_path(@chat), :method => :post, :data => {:confirm => _("Are you sure?")}

app/views/chatty/messages/_form.html.haml
= simple_form_for @message, :remote => true do |f|
  = f.input :chat_id, :as => :hidden
  = f.input :message, :as => :string
  = f.submit class: "chatty_send_msg"

app/views/chatty/messages/new.html.haml
= render "form"